### ISSUE TITLE
createNavigationReducer on Web

### ISSUE THREAD

**Issue by luisrivas** [react-navigation/redux-helpers#96]
I'm trying to use this library with my react-native-web App, but I'm receiving `TypeError: Cannot read property 'getStateForAction' of undefined` when I try to build for web (works fine on mobile)

My screen:
<img width="1123" alt="Screen Shot 2019-09-16 at 1 23 45 PM" src="https://user-images.githubusercontent.com/2474521/64979385-9d21d180-d885-11e9-8e45-6ce2bbfa19bc.png">

Navigator config:
```
import { createBrowserApp } from '@react-navigation/web';
import { createSwitchNavigator } from 'react-navigation';
import MainTabNavigator from './MainTabNavigator';

const switchNavigator = createSwitchNavigator({
  Main: MainTabNavigator,
});
switchNavigator.path = '';

export default createBrowserApp(switchNavigator, { history: 'hash' });
```
Reducer:
```
import { combineReducers } from 'redux';
import { createNavigationReducer } from 'react-navigation-redux-helpers';

const reducers = {
  navigation: createNavigationReducer(AppNavigator),
};

export default combineReducers(reducers);
```

middleware:
```
import thunkMiddleware from 'redux-thunk';
import { createReactNavigationReduxMiddleware } from 'react-navigation-redux-helpers';

export default [thunkMiddleware, createReactNavigationReduxMiddleware(state => state.navigation)];
```

Navigator View Container
```
import { connect } from 'react-redux';
import { createReduxContainer } from 'react-navigation-redux-helpers';
import AppNavigator from './AppNavigator';

const App = createReduxContainer(AppNavigator);

const mapStateToProps = state => ({
  state: state.navigation,
});

export default connect(mapStateToProps)(App);
```

**Comment by Ashoat** [comment]
Hi @luisrivas! Awesome that you're trying to get this library to work with `react-native-web`. I've never tried before, and don't have the bandwidth right now to give it a go, but since this lib is pure-JS and doesn't rely on anything native-specific I imagine it should work pretty easily.

The error you're seeing indicates that the parameter you passed into `createNavigationReducer` - `AppNavigator` - doesn't have a `router` property. Every navigator in React Navigation should be a React Component with a `router` static.

Based on the code snippets you've provided, it appears that what you export from your navigator config is actually a container. `createBrowserApp` appears to take in a navigator, but doesn't actually return a navigator.

Some options:

1. You could try to manually assign the `router` static to the result of `createBrowserApp` and see if that makes things work. For completeness, you could hoist the rest of the React Navigation statics using something like the `hoist-non-react-statics` library.
2. You could try to make this work without `createBrowserApp`. I'm not familiar with the new `react-native-web` support in React Navigation yet, so I'm not sure if this is possible or how easy it would be.
3. If something in `createBrowserApp` is necessary, you could try and build a new `createReduxBrowserApp`. Alternately, you could try and take whatever logic in `createBrowserApp` is necessary for `react-native-web` to work, and move it to a custom navigator that could wrap your current root navigator.

Just to reiterate, as mentioned above I unfortunately don't have the cycles right now to dedicate to trying to make this work. Good luck! If you figure things out, please report back :)
