### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by fabioplaka** [react-navigation/redux-helpers#98]
Hello,
I have an error with the library in react-native app. The application is open successfully but when I go to login, it gives me error that say:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of NavigatorReduxWrapper.

Please if anyone has this error before, give me a solution.
![Simulator Screen Shot - iPhone XS Max - 2019-09-27 at 11 14 28](https://user-images.githubusercontent.com/32648013/65758081-b560de80-e118-11e9-86e9-54c23149f322.png)

**Comment by hight89** [comment]
Hello, i have same problem.

"react-navigation-redux-helpers": "3.0.6",    
"react-navigation": "3.13.0"

If i delete the <ThemeProvider> component from the render method it's works fine.

I know it's not a solution. But i can continue my work, and maybe help for a solution.

**Comment by fabioplaka** [comment]
Same error. Please show me in which class did you delete component from render method?

**Comment by hight89** [comment]
I just delete 91. and 98. row from  the 
/node_modules/react-navigation-redux-helpers/src/create-redux-container.js

I know if i reinstall node modules this change is lost, but i  believe somebody will resolve this soon.

**Comment by hight89** [comment]
> Hello, i have same problem.
> 
> "react-navigation-redux-helpers": "3.0.6",
> "react-navigation": "3.13.0"
> 
> If i delete the component from the render method it's works fine.
> 
> I know it's not a solution. But i can continue my work, and maybe help for a solution.

Upgrade "react-navigation" 4.x or downgrade react-navigation-redux-helpers!

**Comment by Ashoat** [comment]
Oopsie. React Navigation 3.12 has `ThemeContext`, but doesn't have `ThemeProvider` (which is just `ThemeContext.provider`. But earlier versions of React Navigation 3 doesn't have either.

In retrospect this is a breaking change since this library no longer works with React Navigation 3.11 or earlier. I'm going to back out the `ThemeContext` usage and release a 3.0.7 version. And then I'll release a new 4.0 that uses `ThemeContext.provider` so that it works with either React Navigation 3.12 or 4.0.

Thanks for the report and sorry for the mix-up!

**Comment by Ashoat** [comment]
Okay, so:

- If you're using `react-navigation@3.11` or earlier, update to `react-navigation-redux-helpers@3.0.7`
- If you're using `react-navigation@3.12` or later, update to `react-navigation-redux-helpers@4.0.0`
